"""
Generates notebooks 02-07 as .ipynb files.
Run from the repo root: python scripts/generate_notebooks.py
"""

import json
import os

NOTEBOOKS_DIR = os.path.join(os.path.dirname(__file__), '..', 'notebooks')


def md(*lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': '\n'.join(lines)}


def code(*lines):
    return {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': '\n'.join(lines),
    }


def notebook(cells):
    return {
        'nbformat': 4,
        'nbformat_minor': 5,
        'metadata': {
            'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
            'language_info': {'name': 'python', 'version': '3.11.0'},
        },
        'cells': cells,
    }


# ---------------------------------------------------------------------------
# NOTEBOOK 02 — Data Validation
# ---------------------------------------------------------------------------

NB02 = notebook([
    md(
        '# 02 — Data Validation',
        '',
        'Before running any statistical test, we need to verify the data is trustworthy.',
        'Garbage in, garbage out — a beautiful p-value on corrupted data is meaningless.',
        '',
        'This notebook covers:',
        '',
        '1. **Loading the dataset** (real or synthetic fallback)',
        '2. **Basic quality checks** — nulls, types, duplicates',
        '3. **Mismatched records** — users assigned to the wrong page',
        '4. **Sample Ratio Mismatch (SRM)** — was randomization healthy?',
        '5. **Baseline sanity check** — do conversion rates look plausible?',
        '6. **Saving the clean dataset** for downstream notebooks',
        '',
        '---',
        '',
        '> **Dataset:** `data/ab_data.csv` from Kaggle (see CLAUDE.md for download link).',
        '> If the file is not present, synthetic data mirroring the real dataset is generated.',
    ),

    code(
        'import os, sys',
        'import numpy as np',
        'import pandas as pd',
        'import matplotlib.pyplot as plt',
        'import seaborn as sns',
        'from scipy import stats',
        '',
        'sys.path.append("../src")',
        'from ab_stats import check_sample_ratio_mismatch',
        '',
        'sns.set_theme(style="whitegrid", palette="muted")',
        'plt.rcParams["figure.dpi"] = 120',
        '',
        'DATA_PATH  = "../data/ab_data.csv"',
        'CLEAN_PATH = "../data/ab_data_clean.csv"',
    ),

    md('## 1. Load Data'),

    code(
        'def make_synthetic():',
        '    """Synthetic dataset mirroring the Kaggle landing page A/B test."""',
        '    np.random.seed(42)',
        '    n_c, n_t = 147_202, 147_382',
        '    timestamps = pd.date_range("2017-01-02", periods=23, freq="D")',
        '',
        '    def make_group(n, group, page, rate, id_start):',
        '        ts = np.random.choice(timestamps, size=n)',
        '        return pd.DataFrame({',
        '            "user_id":      np.arange(id_start, id_start + n),',
        '            "timestamp":    ts,',
        '            "group":        group,',
        '            "landing_page": page,',
        '            "converted":    np.random.binomial(1, rate, n),',
        '        })',
        '',
        '    ctrl = make_group(n_c, "control",   "old_page", 0.1188, 1)',
        '    trt  = make_group(n_t, "treatment", "new_page", 0.1171, n_c + 1)',
        '',
        '    # Inject ~1% mismatched records (real dataset has these)',
        '    mismatch_idx = ctrl.sample(frac=0.005, random_state=1).index',
        '    ctrl.loc[mismatch_idx, "landing_page"] = "new_page"',
        '    mismatch_idx = trt.sample(frac=0.005, random_state=2).index',
        '    trt.loc[mismatch_idx, "landing_page"] = "old_page"',
        '',
        '    # Inject a handful of duplicate user_ids',
        '    dupes = ctrl.sample(50, random_state=3).copy()',
        '    df = pd.concat([ctrl, trt, dupes]).sample(frac=1, random_state=42).reset_index(drop=True)',
        '    return df',
        '',
        '',
        'if os.path.exists(DATA_PATH):',
        '    df = pd.read_csv(DATA_PATH)',
        '    print(f"Loaded real data: {df.shape[0]:,} rows")',
        '    SYNTHETIC = False',
        'else:',
        '    df = make_synthetic()',
        '    print(f"Real data not found — using synthetic data: {df.shape[0]:,} rows")',
        '    SYNTHETIC = True',
        '',
        'df.head()',
    ),

    md(
        '## 2. Basic Quality Checks',
        '',
        'Start with the boring stuff. Issues here invalidate everything downstream.',
    ),

    code(
        'print("Shape:", df.shape)',
        'print()',
        'print("Dtypes:")',
        'print(df.dtypes)',
        'print()',
        'print("Null counts:")',
        'print(df.isnull().sum())',
        'print()',
        'print("Unique users:", df["user_id"].nunique())',
        'print("Total rows:  ", len(df))',
    ),

    code(
        '# Duplicate user_ids — a user appearing twice is not two independent observations',
        'n_dupes = df.duplicated(subset="user_id").sum()',
        'print(f"Duplicate user_id rows: {n_dupes:,}")',
        '',
        'df = df.drop_duplicates(subset="user_id", keep="first")',
        'print(f"After dedup: {len(df):,} rows")',
    ),

    md(
        '## 3. Mismatched Records',
        '',
        'In a correctly implemented experiment, every user in the **control** group sees the **old page**',
        'and every user in the **treatment** group sees the **new page**. A mismatch means the',
        'assignment logic had a bug — those users saw the wrong experience.',
        '',
        'Rows where `group == "treatment"` but `landing_page == "old_page"` (and vice versa)',
        'must be dropped. Keeping them contaminates both groups.',
    ),

    code(
        'mismatch = (',
        '    ((df["group"] == "control")   & (df["landing_page"] == "new_page")) |',
        '    ((df["group"] == "treatment") & (df["landing_page"] == "old_page"))',
        ')',
        'print(f"Mismatched records: {mismatch.sum():,} ({mismatch.mean():.2%} of data)")',
        '',
        'df = df[~mismatch].reset_index(drop=True)',
        'print(f"After removing mismatches: {len(df):,} rows")',
    ),

    md(
        '## 4. Sample Ratio Mismatch (SRM)',
        '',
        'We expect a 50/50 split between control and treatment. If the actual split is meaningfully',
        'different, the randomization is broken — and the experiment results cannot be trusted,',
        'even if the p-value looks clean.',
        '',
        '**SRM is checked with a chi-square goodness-of-fit test** against the expected split.',
        'We use α = 0.01 (stricter than the main analysis) because SRM is a data quality gate,',
        'not a scientific hypothesis.',
    ),

    code(
        'counts = df["group"].value_counts()',
        'n_control   = counts.get("control",   0)',
        'n_treatment = counts.get("treatment", 0)',
        'print(f"Control:   {n_control:,}")',
        'print(f"Treatment: {n_treatment:,}")',
        'print(f"Ratio:     {n_control / (n_control + n_treatment):.4f} / {n_treatment / (n_control + n_treatment):.4f}")',
        '',
        'srm, chi2, p_srm = check_sample_ratio_mismatch(n_control, n_treatment)',
        'print()',
        'print(f"Chi-square statistic: {chi2:.4f}")',
        'print(f"p-value:              {p_srm:.4f}")',
        'print(f"SRM detected:         {srm}")',
        'print()',
        'if srm:',
        '    print("WARNING: SRM detected. Investigate randomization before proceeding.")',
        'else:',
        '    print("No SRM detected. Randomization looks healthy.")',
    ),

    md(
        '## 5. Baseline Sanity Check',
        '',
        'Before running the experiment analysis, verify that conversion rates are in the expected',
        'ballpark. A rate of 0% or 99% usually signals a tracking bug, not a real effect.',
    ),

    code(
        'summary = df.groupby("group")["converted"].agg(["sum", "count", "mean"])',
        'summary.columns = ["conversions", "users", "conversion_rate"]',
        'summary["conversion_rate"] = summary["conversion_rate"].map("{:.2%}".format)',
        'print(summary)',
        '',
        'fig, ax = plt.subplots(figsize=(6, 3.5))',
        'rates = df.groupby("group")["converted"].mean()',
        'bars = ax.bar(rates.index, rates.values * 100, color=["steelblue", "coral"], width=0.5)',
        'ax.set_ylim(0, rates.max() * 100 * 1.4)',
        'ax.set_ylabel("Conversion rate (%)")',
        'ax.set_title("Conversion rates by group (pre-analysis sanity check)")',
        'for bar, rate in zip(bars, rates.values):',
        '    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1,',
        '            f"{rate:.2%}", ha="center", va="bottom", fontweight="bold")',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md('## 6. Save Clean Dataset'),

    code(
        'os.makedirs("../data", exist_ok=True)',
        'df.to_csv(CLEAN_PATH, index=False)',
        'print(f"Clean dataset saved to {CLEAN_PATH}")',
        'print(f"Final shape: {df.shape[0]:,} rows x {df.shape[1]} columns")',
    ),

    md(
        '## Summary',
        '',
        '| Check | Result |',
        '|---|---|',
        '| Null values | None |',
        '| Duplicate user IDs | Removed (keep first) |',
        '| Mismatched page assignments | Removed |',
        '| Sample Ratio Mismatch | Not detected |',
        '| Conversion rate range | ~12% — plausible |',
        '',
        'Data is clean. Proceed to **[03 — Statistical Analysis](03_statistical_analysis.ipynb)**.',
    ),
])

# ---------------------------------------------------------------------------
# NOTEBOOK 03 — Statistical Analysis
# ---------------------------------------------------------------------------

NB03 = notebook([
    md(
        '# 03 — Statistical Analysis',
        '',
        'With clean data in hand, we run the core statistical test.',
        '',
        'This notebook covers:',
        '',
        '1. **Computing conversion rates** per group',
        '2. **The two-proportion z-test** — why it, how it works',
        '3. **Interpreting p-values** — what they mean and what they do NOT mean',
        '4. **Confidence intervals** — a richer picture than a single p-value',
        '5. **Visualizing the result** — sampling distribution and CI plots',
    ),

    code(
        'import sys, os',
        'import numpy as np',
        'import pandas as pd',
        'import matplotlib.pyplot as plt',
        'import matplotlib.patches as mpatches',
        'import seaborn as sns',
        'from scipy import stats',
        '',
        'sys.path.append("../src")',
        'from ab_stats import two_proportion_ztest, confidence_interval',
        '',
        'sns.set_theme(style="whitegrid", palette="muted")',
        'plt.rcParams["figure.dpi"] = 120',
        '',
        'ALPHA = 0.05',
        '',
        'df = pd.read_csv("../data/ab_data_clean.csv")',
        'print(f"Loaded: {len(df):,} rows")',
        'df.head(3)',
    ),

    md('## 1. Conversion Rates'),

    code(
        'grp = df.groupby("group")["converted"].agg(conversions="sum", users="count")',
        'grp["rate"] = grp["conversions"] / grp["users"]',
        '',
        'ctrl = grp.loc["control"]',
        'trt  = grp.loc["treatment"]',
        '',
        'print(f"Control   — users: {ctrl.users:>8,}  conversions: {ctrl.conversions:>7,}  rate: {ctrl.rate:.4%}")',
        'print(f"Treatment — users: {trt.users:>8,}  conversions: {trt.conversions:>7,}  rate: {trt.rate:.4%}")',
        'print(f"Absolute difference: {trt.rate - ctrl.rate:+.4%}")',
        'print(f"Relative difference: {(trt.rate - ctrl.rate) / ctrl.rate:+.2%}")',
    ),

    md(
        '## 2. The Two-Proportion Z-Test',
        '',
        'We use a **two-proportion z-test** because:',
        '- The outcome is binary (converted: 0 or 1)',
        '- Sample sizes are large (N >> 30), so the Central Limit Theorem applies',
        '- We have two independent groups',
        '',
        '### How it works',
        '',
        'Under H₀ (no difference), the test statistic is:',
        '',
        '$$z = \\frac{\\hat{p}_T - \\hat{p}_C}{\\sqrt{\\hat{p}(1-\\hat{p})\\left(\\frac{1}{n_C} + \\frac{1}{n_T}\\right)}}$$',
        '',
        'where $\\hat{p}$ is the **pooled proportion** — the overall conversion rate across both groups.',
        '',
        'If H₀ were true, this z-statistic would follow a standard normal distribution N(0,1).',
        'We check how extreme our observed z is under that distribution.',
    ),

    code(
        'z, p_val, p_c, p_t, lift_abs, lift_rel = two_proportion_ztest(',
        '    ctrl.conversions, ctrl.users,',
        '    trt.conversions,  trt.users,',
        ')',
        '',
        'print("=" * 45)',
        'print("  Two-Proportion Z-Test Results")',
        'print("=" * 45)',
        'print(f"  Control rate   : {p_c:.4%}")',
        'print(f"  Treatment rate : {p_t:.4%}")',
        'print(f"  Absolute lift  : {lift_abs:+.4%}")',
        'print(f"  Relative lift  : {lift_rel:+.2%}")',
        'print(f"  z-statistic    : {z:.4f}")',
        'print(f"  p-value        : {p_val:.4f}")',
        'print(f"  alpha          : {ALPHA}")',
        'print()',
        'if p_val < ALPHA:',
        '    print("  RESULT: Reject H0 — statistically significant")',
        'else:',
        '    print("  RESULT: Fail to reject H0 — not statistically significant")',
        'print("=" * 45)',
    ),

    md(
        '## 3. Interpreting the p-value',
        '',
        'The p-value is one of the most misunderstood numbers in science.',
        '',
        '### What p-value IS',
        '',
        '> The probability of observing a result **at least as extreme as ours**, *assuming H₀ is true*.',
        '',
        'In plain English: if the new page truly had zero effect, how often would random chance',
        'produce a difference this large or larger? A large p-value means "often" — the data is',
        'consistent with there being no real effect.',
        '',
        '### What p-value is NOT',
        '',
        '| Misconception | Reality |',
        '|---|---|',
        '| p = 0.19 means 19% chance the null is true | p-value says nothing about P(H₀ is true) |',
        '| p < 0.05 means the effect is real | It means the data is unlikely under H₀; the effect could still be noise |',
        '| p > 0.05 means no effect exists | "Absence of evidence is not evidence of absence" |',
        '| A smaller p-value means a bigger effect | p-value conflates effect size and sample size |',
        '| p-value tells us the effect is practically meaningful | That requires effect size + business context |',
        '',
        '**The p-value is a measure of surprise, not a measure of importance.**',
    ),

    code(
        '# Visualize the null distribution and where our test statistic falls',
        'x = np.linspace(-4, 4, 400)',
        'y = stats.norm.pdf(x)',
        '',
        'fig, ax = plt.subplots(figsize=(9, 4))',
        'ax.plot(x, y, color="steelblue", linewidth=2, label="N(0,1) under H₀")',
        '',
        '# Shade rejection regions (two-tailed)',
        'crit = stats.norm.ppf(1 - ALPHA / 2)',
        'ax.fill_between(x, y, where=(x <= -crit), color="tomato", alpha=0.3, label=f"Rejection region (α={ALPHA})")',
        'ax.fill_between(x, y, where=(x >=  crit), color="tomato", alpha=0.3)',
        '',
        '# Mark observed z',
        'ax.axvline(z, color="darkgreen", linewidth=2, linestyle="--", label=f"Observed z = {z:.2f}")',
        'ax.axvline(-crit, color="tomato", linewidth=1, linestyle=":")',
        'ax.axvline( crit, color="tomato", linewidth=1, linestyle=":")',
        '',
        'ax.set_xlabel("z-statistic", fontsize=11)',
        'ax.set_ylabel("Density", fontsize=11)',
        'ax.set_title("Sampling distribution under H₀ — where does our z land?", fontsize=13)',
        'ax.legend()',
        'plt.tight_layout()',
        'plt.show()',
        '',
        'print(f"Critical value: ±{crit:.2f}")',
        'inside_outside = "INSIDE" if abs(z) < crit else "OUTSIDE"',
        'print(f"Our z = {z:.2f} is {inside_outside} the non-rejection region")',
    ),

    md(
        '## 4. Confidence Intervals',
        '',
        'A confidence interval gives a **range of plausible values** for the true conversion rate.',
        'It is more informative than a single point estimate.',
        '',
        'We use the **Wilson score interval** — it works well even near 0 or 1 and for',
        'moderate sample sizes, unlike the simpler normal approximation interval.',
        '',
        'A 95% CI means: if we ran this experiment 100 times and computed a CI each time,',
        '95 of those intervals would contain the true population proportion.',
        '*(It does NOT mean "95% chance the true value is in this specific interval.")*',
    ),

    code(
        'ci_c = confidence_interval(ctrl.conversions, ctrl.users, ALPHA)',
        'ci_t = confidence_interval(trt.conversions,  trt.users,  ALPHA)',
        '',
        'print(f"Control   95% CI: [{ci_c[0]:.4%}, {ci_c[1]:.4%}]  (point: {p_c:.4%})")',
        'print(f"Treatment 95% CI: [{ci_t[0]:.4%}, {ci_t[1]:.4%}]  (point: {p_t:.4%})")',
        '',
        '# Plot',
        'fig, ax = plt.subplots(figsize=(7, 3.5))',
        'groups = ["Control", "Treatment"]',
        'means  = [p_c, p_t]',
        'errs   = [[m - lo for m, (lo, _) in zip(means, [ci_c, ci_t])],',
        '          [hi - m for m, (_, hi) in zip(means, [ci_c, ci_t])]]',
        '',
        'ax.barh(groups, [m * 100 for m in means], xerr=[[e*100 for e in errs[0]], [e*100 for e in errs[1]]],',
        '        color=["steelblue", "coral"], capsize=6, height=0.4)',
        'ax.set_xlabel("Conversion rate (%)")',
        'ax.set_title("Conversion rates with 95% confidence intervals")',
        'ax.set_xlim(10, 14)',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## 5. Visualizing the Difference',
        '',
        'Instead of just looking at each group separately, we can compute a CI directly on',
        'the **difference** between treatment and control. This is what we actually care about.',
    ),

    code(
        '# CI on the difference using normal approximation',
        'se_diff = np.sqrt(p_c*(1-p_c)/ctrl.users + p_t*(1-p_t)/trt.users)',
        'z_crit  = stats.norm.ppf(1 - ALPHA/2)',
        'diff_lo = lift_abs - z_crit * se_diff',
        'diff_hi = lift_abs + z_crit * se_diff',
        '',
        'print(f"Observed difference: {lift_abs:+.4%}")',
        'print(f"95% CI on diff:      [{diff_lo:+.4%}, {diff_hi:+.4%}]")',
        'print()',
        'contains_zero = diff_lo < 0 < diff_hi',
        'h0_label = "consistent with H0" if contains_zero else "excludes H0"',
        'print(f"CI contains zero: {contains_zero} — {h0_label}")',
        '',
        'fig, ax = plt.subplots(figsize=(8, 3))',
        'ax.axvline(0, color="gray", linewidth=1.2, linestyle="--", label="No effect (H₀)")',
        'ax.errorbar(lift_abs * 100, 0.5, xerr=[[abs(diff_lo-lift_abs)*100], [abs(diff_hi-lift_abs)*100]],',
        '            fmt="o", color="steelblue", capsize=8, markersize=8, linewidth=2,',
        '            label=f"Observed lift + 95% CI")',
        'ax.set_xlabel("Difference in conversion rate (percentage points)")',
        'ax.set_yticks([])',
        'ax.set_title("95% CI on treatment vs. control difference")',
        'ax.legend()',
        'ax.set_xlim(-0.5, 0.5)',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## Summary',
        '',
        f'| Metric | Value |',
        '|---|---|',
        '| Control conversion rate | ~11.9% |',
        '| Treatment conversion rate | ~11.7% |',
        '| Absolute difference | ~−0.2pp |',
        '| p-value | ~0.19 |',
        '| 95% CI on difference | contains zero |',
        '| Decision | Fail to reject H₀ |',
        '',
        '**We cannot conclude the new landing page improves conversion.** The observed difference',
        'is small and consistent with random variation.',
        '',
        'But statistical significance alone does not tell the whole story.',
        'Proceed to **[04 — Practical Significance](04_practical_significance.ipynb)**',
        'to understand *how big* an effect we could have detected.',
    ),
])

# ---------------------------------------------------------------------------
# NOTEBOOK 04 — Practical Significance
# ---------------------------------------------------------------------------

NB04 = notebook([
    md(
        '# 04 — Practical Significance',
        '',
        '**Statistical significance** answers: "Is the effect distinguishable from zero?"',
        '**Practical significance** answers: "Is the effect large enough to matter?"',
        '',
        'These are different questions. A test with millions of users can detect a 0.001pp lift',
        'as statistically significant — but that lift might not be worth the engineering cost.',
        'Conversely, our test might have been *underpowered* to detect an effect that would',
        'have mattered. This notebook unpacks both scenarios.',
        '',
        'This notebook covers:',
        '',
        '1. **Effect size (Cohen\'s h)** — a standardized, sample-size-independent measure',
        '2. **CI on the difference vs. MDE** — did we actually rule out meaningful effects?',
        '3. **Retrospective power** — what could we have detected with our actual N?',
        '4. **Four-quadrant decision framework** — the full decision matrix',
    ),

    code(
        'import sys',
        'import numpy as np',
        'import pandas as pd',
        'import matplotlib.pyplot as plt',
        'import matplotlib.patches as mpatches',
        'from scipy import stats',
        '',
        'sys.path.append("../src")',
        'from ab_stats import two_proportion_ztest, confidence_interval, cohens_h, sample_size_per_group',
        '',
        'import matplotlib; matplotlib.rcParams["figure.dpi"] = 120',
        'import seaborn as sns; sns.set_theme(style="whitegrid")',
        '',
        'ALPHA = 0.05',
        'MDE   = 0.02   # minimum detectable effect from experiment design',
        '',
        'df = pd.read_csv("../data/ab_data_clean.csv")',
        'grp = df.groupby("group")["converted"].agg(conversions="sum", users="count")',
        'grp["rate"] = grp["conversions"] / grp["users"]',
        'ctrl, trt = grp.loc["control"], grp.loc["treatment"]',
        '',
        'z, p_val, p_c, p_t, lift_abs, lift_rel = two_proportion_ztest(',
        '    ctrl.conversions, ctrl.users, trt.conversions, trt.users',
        ')',
        'print(f"p-value: {p_val:.4f} | lift: {lift_abs:+.4%}")',
    ),

    md(
        '## 1. Effect Size: Cohen\'s h',
        '',
        "Cohen's h is a standardized effect size for proportions. Unlike the raw difference,",
        'it accounts for the fact that a 2pp difference at 10% baseline is more meaningful',
        'than the same 2pp difference at 50% baseline.',
        '',
        '$$h = 2\\arcsin(\\sqrt{p_1}) - 2\\arcsin(\\sqrt{p_2})$$',
        '',
        '| |h| | Interpretation |',
        '|---|---|',
        '| < 0.20 | Small |',
        '| 0.20 – 0.50 | Medium |',
        '| > 0.50 | Large |',
        '',
        'Small does not mean unimportant — at high-traffic scale, even small effects compound.',
    ),

    code(
        'h = cohens_h(p_t, p_c)',
        'print(f"Cohen\'s h: {h:.4f}")',
        '',
        'if abs(h) < 0.20:',
        '    label = "Small"',
        'elif abs(h) < 0.50:',
        '    label = "Medium"',
        'else:',
        '    label = "Large"',
        '',
        'print(f"Effect size category: {label}")',
        'print()',
        'print("Context: Cohen\'s h for our MDE (+2pp at 12% baseline):")',
        'print(f"  h_MDE = {cohens_h(0.14, 0.12):.4f}")',
        'print(f"  Our observed h = {abs(h):.4f} — well below MDE threshold")',
    ),

    md(
        '## 2. CI on the Difference vs. MDE Threshold',
        '',
        'The key practical significance question: **does our confidence interval rule out',
        'effects that would matter to the business?**',
        '',
        'If the CI includes the MDE, we cannot conclude the true effect is below our business',
        'threshold. The experiment is *inconclusive*, not *negative*.',
    ),

    code(
        'se_diff = np.sqrt(p_c*(1-p_c)/ctrl.users + p_t*(1-p_t)/trt.users)',
        'z_crit  = stats.norm.ppf(1 - ALPHA/2)',
        'diff_lo = lift_abs - z_crit * se_diff',
        'diff_hi = lift_abs + z_crit * se_diff',
        '',
        'fig, ax = plt.subplots(figsize=(9, 3.5))',
        '',
        '# MDE threshold lines',
        'ax.axvspan(-MDE*100, MDE*100, color="gold", alpha=0.25, label=f"Practically insignificant zone (|effect| < MDE={MDE:.0%})")',
        'ax.axvline(0, color="gray", linewidth=1.2, linestyle="--")',
        '',
        '# CI on difference',
        'ax.errorbar(lift_abs*100, 0.5,',
        '            xerr=[[abs(diff_lo - lift_abs)*100], [abs(diff_hi - lift_abs)*100]],',
        '            fmt="o", color="steelblue", capsize=10, markersize=9, linewidth=2.5,',
        '            label=f"Observed lift {lift_abs:+.2%} with 95% CI")',
        '',
        'ax.set_yticks([])',
        'ax.set_xlabel("Difference in conversion rate (percentage points)", fontsize=11)',
        'ax.set_title("95% CI on lift vs. minimum detectable effect", fontsize=13)',
        'ax.legend(loc="upper right")',
        'ax.set_xlim(-2.5, 2.5)',
        'plt.tight_layout()',
        'plt.show()',
        '',
        'print(f"95% CI: [{diff_lo:+.4%}, {diff_hi:+.4%}]")',
        'print(f"CI upper bound ({diff_hi:+.4%}) vs MDE ({MDE:+.4%}): ", end="")',
        'print("CI excludes MDE" if diff_hi < MDE else "CI does NOT exclude MDE — result is inconclusive")',
    ),

    md(
        '## 3. Retrospective Power',
        '',
        'Given our **actual sample size**, what was the smallest effect we could reliably detect?',
        '',
        'This is the "achieved MDE" — useful for interpreting a non-significant result.',
        'If the achieved MDE is larger than effects that matter to the business, the',
        'experiment was underpowered and the null result is uninformative.',
    ),

    code(
        'from ab_stats import sample_size_per_group',
        'actual_n = min(ctrl.users, trt.users)',
        '',
        '# Find the MDE achievable at our actual N (binary search)',
        'lo, hi = 0.001, 0.50',
        'for _ in range(50):',
        '    mid = (lo + hi) / 2',
        '    if sample_size_per_group(p_c, mid) <= actual_n:',
        '        hi = mid',
        '    else:',
        '        lo = mid',
        'achieved_mde = hi',
        '',
        'print(f"Actual N per group : {actual_n:,}")',
        'print(f"Achieved MDE       : {achieved_mde:+.4%} (at 80% power, α=0.05)")',
        'print(f"Our planned MDE    : {MDE:+.4%}")',
        'print()',
        'if achieved_mde <= MDE:',
        '    print("The experiment was adequately powered to detect the MDE we cared about.")',
        'else:',
        '    print("WARNING: The experiment was underpowered. Non-significant result may reflect")',
        '    print("insufficient sample size, not absence of an effect.")',
    ),

    md(
        '## 4. The Four-Quadrant Decision Framework',
        '',
        'Every A/B test result falls into one of four quadrants. The action depends on **both**',
        'statistical significance and practical significance.',
        '',
        '|  | **Practically significant** | **Practically insignificant** |',
        '|---|---|---|',
        '| **Statistically significant** | Ship it | Investigate — may not be worth shipping |',
        '| **Not statistically significant** | Inconclusive — rerun with more data | Do not ship |',
        '',
        '### Our result',
        '',
        'Our p-value is ~0.19 (not significant). The 95% CI on the difference spans both sides',
        'of the MDE threshold. We are in the **bottom-left quadrant**: inconclusive.',
        '',
        'This does NOT mean the page is bad. It means we do not have enough evidence to decide.',
        '',
        '**Business options:**',
        '1. Run a longer / larger experiment to get a definitive answer',
        '2. Kill the experiment if the cost of running it exceeds the expected value of the information',
        '3. Iterate on the design before re-testing — if the current design can\'t move the needle, try a bigger change',
    ),

    code(
        '# Illustrate all four quadrants with synthetic scenarios',
        'scenarios = [',
        '    ("Scenario A\\nSig + Practical", 0.025, 0.005, "Ship it", "green"),',
        '    ("Scenario B\\nSig + Not Practical", 0.0001, 0.049, "Probably not worth shipping", "orange"),',
        '    ("Scenario C (ours)\\nNot Sig + Inconclusive", lift_abs, p_val, "Inconclusive — more data", "steelblue"),',
        '    ("Scenario D\\nNot Sig + Tiny effect", -0.0005, 0.80, "Do not ship", "tomato"),',
        ']',
        '',
        'fig, axes = plt.subplots(1, 4, figsize=(14, 4))',
        'for ax, (title, lift, pv, action, color) in zip(axes, scenarios):',
        '    se = 0.002',
        '    lo = lift - 1.96 * se',
        '    hi = lift + 1.96 * se',
        '    ax.axvspan(-MDE*100, MDE*100, color="gold", alpha=0.2)',
        '    ax.axvline(0, color="gray", linewidth=1, linestyle="--")',
        '    ax.errorbar(lift*100, 0.5, xerr=[[abs(lo-lift)*100],[abs(hi-lift)*100]],',
        '                fmt="o", color=color, capsize=7, markersize=8, linewidth=2)',
        '    ax.set_xlim(-3.5, 3.5)',
        '    ax.set_yticks([])',
        '    ax.set_xlabel("Lift (pp)")',
        '    ax.set_title(title, fontsize=9)',
        '    ax.text(0.5, 0.05, action, ha="center", transform=ax.transAxes,',
        '            fontsize=8, color=color, fontweight="bold")',
        '',
        'plt.suptitle("Four-quadrant decision framework", fontsize=12, y=1.02)',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## Summary',
        '',
        '- **Statistical significance** tells us if the signal exceeds noise — it does not tell us if it matters',
        '- **Cohen\'s h** standardizes the effect size independent of sample size',
        '- **The CI vs. MDE comparison** is the right way to assess practical significance',
        '- **Retrospective power** explains whether a null result is informative or just underpowered',
        '- Our result: inconclusive — the experiment cannot rule out a meaningful effect',
        '',
        'Proceed to **[05 — Segment Analysis](05_segment_analysis.ipynb)**.',
    ),
])

# ---------------------------------------------------------------------------
# NOTEBOOK 05 — Segment Analysis
# ---------------------------------------------------------------------------

NB05 = notebook([
    md(
        '# 05 — Segment Analysis',
        '',
        'Aggregate results can hide important patterns. Segment analysis asks:',
        '',
        '- Does the treatment effect hold across all user groups?',
        '- Is the effect driven by a specific subgroup?',
        '- Are there groups being harmed while the average looks neutral?',
        '',
        'This notebook covers:',
        '',
        '1. **Temporal analysis** — does the effect change over time? (novelty effect)',
        '2. **Day-of-week analysis** — is behavior consistent across the week?',
        '3. **Simpson\'s Paradox** — how aggregation can reverse or mask effects',
        '4. **Interaction effects** — formally testing heterogeneous treatment effects',
        '5. **Practical guardrails** — pre-specification and multiple testing preview',
    ),

    code(
        'import sys',
        'import numpy as np',
        'import pandas as pd',
        'import matplotlib.pyplot as plt',
        'import seaborn as sns',
        'from scipy import stats',
        '',
        'sys.path.append("../src")',
        'from ab_stats import two_proportion_ztest, confidence_interval',
        '',
        'sns.set_theme(style="whitegrid", palette="muted")',
        'plt.rcParams["figure.dpi"] = 120',
        '',
        'ALPHA = 0.05',
        '',
        'df = pd.read_csv("../data/ab_data_clean.csv", parse_dates=["timestamp"])',
        'df["weekday"]  = df["timestamp"].dt.day_name()',
        'df["week_num"] = (df["timestamp"] - df["timestamp"].min()).dt.days // 7 + 1',
        'df["is_weekend"] = df["weekday"].isin(["Saturday", "Sunday"])',
        '',
        'print(f"Date range: {df.timestamp.min().date()} to {df.timestamp.max().date()}")',
        'print(f"Weeks in experiment: {df.week_num.max()}")',
    ),

    md(
        '## 1. Temporal Analysis — Novelty Effect',
        '',
        'When a new design launches, users may engage with it simply because it\'s new.',
        'This **novelty effect** can inflate early results. If the treatment effect shrinks',
        'in later weeks, that\'s a sign you\'re measuring novelty, not genuine improvement.',
        '',
        'Conversely, a **learning effect** means users improve at converting as they get used',
        'to the new design — the effect grows over time.',
    ),

    code(
        'weekly = (',
        '    df.groupby(["week_num", "group"])["converted"]',
        '    .agg(conversions="sum", users="count")',
        '    .reset_index()',
        ')',
        'weekly["rate"] = weekly["conversions"] / weekly["users"]',
        '',
        'fig, ax = plt.subplots(figsize=(9, 4))',
        'for group, color in [("control", "steelblue"), ("treatment", "coral")]:',
        '    sub = weekly[weekly["group"] == group]',
        '    ax.plot(sub["week_num"], sub["rate"] * 100, marker="o",',
        '            color=color, linewidth=2, label=group.title())',
        '    ax.fill_between(sub["week_num"], sub["rate"]*100 - 0.3, sub["rate"]*100 + 0.3,',
        '                    color=color, alpha=0.1)',
        '',
        'ax.set_xlabel("Week of experiment")',
        'ax.set_ylabel("Conversion rate (%)")',
        'ax.set_title("Weekly conversion rates by group — checking for novelty effect")',
        'ax.legend()',
        'plt.tight_layout()',
        'plt.show()',
        '',
        '# Weekly lift',
        'print("Week | Control | Treatment | Lift")',
        'print("-" * 42)',
        'for w in sorted(weekly["week_num"].unique()):',
        '    wk = weekly[weekly["week_num"] == w]',
        '    rc = wk[wk["group"]=="control"]["rate"].values',
        '    rt = wk[wk["group"]=="treatment"]["rate"].values',
        '    if len(rc) and len(rt):',
        '        print(f"  {w}  | {rc[0]:.4%}  | {rt[0]:.4%}     | {rt[0]-rc[0]:+.4%}")',
    ),

    md(
        '## 2. Day-of-Week Analysis',
        '',
        'User behavior varies by day. A test that runs Mon–Thu might show different results',
        'than one running Fri–Sun. We should verify the effect is consistent across all days.',
    ),

    code(
        'day_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]',
        '',
        'daily = (',
        '    df.groupby(["weekday", "group"])["converted"]',
        '    .agg(conversions="sum", users="count")',
        '    .reset_index()',
        ')',
        'daily["rate"] = daily["conversions"] / daily["users"]',
        'daily["weekday"] = pd.Categorical(daily["weekday"], categories=day_order, ordered=True)',
        'daily = daily.sort_values("weekday")',
        '',
        'fig, ax = plt.subplots(figsize=(10, 4))',
        'x = np.arange(7)',
        'w = 0.35',
        'for i, (group, color) in enumerate([("control","steelblue"),("treatment","coral")]):',
        '    sub = daily[daily["group"]==group].set_index("weekday").reindex(day_order)',
        '    ax.bar(x + i*w, sub["rate"]*100, width=w, label=group.title(), color=color, alpha=0.85)',
        '',
        'ax.set_xticks(x + w/2)',
        'ax.set_xticklabels([d[:3] for d in day_order])',
        'ax.set_ylabel("Conversion rate (%)")',
        'ax.set_title("Conversion rate by day of week")',
        'ax.legend()',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## 3. Simpson\'s Paradox',
        '',
        'Simpson\'s Paradox occurs when a trend present in several subgroups **reverses**',
        'when the subgroups are combined. It arises when the subgroups have different sizes',
        'and different baseline rates.',
        '',
        'The landing page dataset does not naturally exhibit this, so we demonstrate it with',
        'a synthetic example using **device type** (mobile vs. desktop) as the confounder.',
        '',
        '**Setup:** Mobile users convert at a lower rate than desktop users. The treatment group',
        'happens to have more mobile users (a randomization imbalance in this dimension).',
        'Aggregate results favor the control — but within each device type, treatment wins.',
    ),

    code(
        '# Synthetic Simpson\'s Paradox demonstration',
        'np.random.seed(99)',
        '',
        '# Desktop: high base rate, treatment wins',
        '# Mobile:  low base rate, treatment wins',
        '# But treatment group has more mobile users — aggregate reverses',
        '',
        'simp = pd.DataFrame({',
        '    "device":    ["desktop"]*40000 + ["mobile"]*10000 + ["desktop"]*20000 + ["mobile"]*30000,',
        '    "group":     ["control"]*50000 + ["treatment"]*50000,',
        '})',
        'desktop_ctrl_rate, desktop_trt_rate = 0.20, 0.22',
        'mobile_ctrl_rate,  mobile_trt_rate  = 0.05, 0.07',
        '',
        'rates = {',
        '    ("control",   "desktop"): desktop_ctrl_rate,',
        '    ("control",   "mobile"):  mobile_ctrl_rate,',
        '    ("treatment", "desktop"): desktop_trt_rate,',
        '    ("treatment", "mobile"):  mobile_trt_rate,',
        '}',
        'simp["converted"] = simp.apply(',
        '    lambda r: np.random.binomial(1, rates[(r.group, r.device)]), axis=1',
        ')',
        '',
        '# Aggregate result',
        'agg = simp.groupby("group")["converted"].mean()',
        'print("AGGREGATE (misleading):")',
        'print(f"  Control:   {agg[\"control\"]:.3%}")',
        'print(f"  Treatment: {agg[\"treatment\"]:.3%}")',
        'print(f"  => Treatment looks WORSE by {agg[\"treatment\"]-agg[\"control\"]:+.3%}")',
        '',
        '# Segment result',
        'print()',
        'print("BY DEVICE (correct):")',
        'seg = simp.groupby(["device","group"])["converted"].mean().unstack()',
        'for device in ["desktop", "mobile"]:',
        '    print(f"  {device}: control={seg.loc[device,\"control\"]:.3%}, treatment={seg.loc[device,\"treatment\"]:.3%}, lift={seg.loc[device,\"treatment\"]-seg.loc[device,\"control\"]:+.3%}")',
        'print(f"  => Treatment is BETTER in BOTH segments")',
        'print()',
        'print("Lesson: Always check whether aggregate results are driven by a confounding variable.")',
    ),

    code(
        '# Visualize the paradox',
        'fig, axes = plt.subplots(1, 3, figsize=(13, 4))',
        '',
        '# Aggregate',
        'ax = axes[0]',
        'ax.bar(["Control","Treatment"], [agg["control"]*100, agg["treatment"]*100],',
        '       color=["steelblue","coral"])',
        'ax.set_title("Aggregate\\n(misleading)", fontsize=11)',
        'ax.set_ylabel("Conversion rate (%)")',
        'ax.set_ylim(0, 25)',
        '',
        '# Desktop',
        'ax = axes[1]',
        'ax.bar(["Control","Treatment"],',
        '       [seg.loc["desktop","control"]*100, seg.loc["desktop","treatment"]*100],',
        '       color=["steelblue","coral"])',
        'ax.set_title("Desktop segment\\n(treatment wins)", fontsize=11)',
        'ax.set_ylim(0, 25)',
        '',
        '# Mobile',
        'ax = axes[2]',
        'ax.bar(["Control","Treatment"],',
        '       [seg.loc["mobile","control"]*100, seg.loc["mobile","treatment"]*100],',
        '       color=["steelblue","coral"])',
        'ax.set_title("Mobile segment\\n(treatment wins)", fontsize=11)',
        'ax.set_ylim(0, 25)',
        '',
        'plt.suptitle("Simpson\'s Paradox: aggregate reverses segment-level truth", fontsize=12)',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## 4. Interaction Effects',
        '',
        'A formal way to ask: "Does the treatment effect differ across segments?"',
        '',
        'We test this by adding a **group × segment interaction term** and checking whether',
        'the interaction coefficient is significant. A significant interaction means the effect',
        'is **heterogeneous** — different users respond differently to the treatment.',
    ),

    code(
        '# Test for interaction between group and weekend/weekday',
        'from scipy.stats import chi2_contingency',
        '',
        'def segment_test(df, segment_col):',
        '    results = []',
        '    for seg_val in df[segment_col].unique():',
        '        sub = df[df[segment_col] == seg_val]',
        '        grp = sub.groupby("group")["converted"].agg(["sum","count"])',
        '        if "control" not in grp.index or "treatment" not in grp.index:',
        '            continue',
        '        z, p, pc, pt, la, lr = two_proportion_ztest(',
        '            grp.loc["control","sum"],   grp.loc["control","count"],',
        '            grp.loc["treatment","sum"],  grp.loc["treatment","count"],',
        '        )',
        '        results.append({"segment": seg_val, "control_rate": pc,',
        '                        "treatment_rate": pt, "lift": la, "p_value": p})',
        '    return pd.DataFrame(results)',
        '',
        'print("=== Weekday vs Weekend ===")',
        'res = segment_test(df, "is_weekend")',
        'res["segment"] = res["segment"].map({True: "Weekend", False: "Weekday"})',
        'print(res.to_string(index=False))',
        '',
        'print()',
        'print("=== By Day of Week ===")',
        'res2 = segment_test(df, "weekday")',
        'print(res2.sort_values("p_value").to_string(index=False))',
    ),

    md(
        '## 5. Guardrails for Segment Analysis',
        '',
        '**Pre-specify your segments.** Running post-hoc segment searches inflates false positive',
        'rates — with 20 segments, you expect 1 significant result by chance at α=0.05.',
        '',
        '| Type | Description | How to handle |',
        '|---|---|---|',
        '| Pre-specified segments | Defined in experiment plan before launch | Test at nominal α |',
        '| Exploratory segments | Discovered by looking at the data | Adjust α (see notebook 06) |',
        '| Guardrail segments | Groups who must not be harmed | One-tailed test, strict α |',
        '',
        '**Segment findings are hypothesis-generating, not hypothesis-confirming.**',
        'A surprising segment result should lead to a new, dedicated experiment for that segment.',
        '',
        'Proceed to **[06 — Multiple Testing](06_multiple_testing.ipynb)** for correction methods.',
    ),
])

# ---------------------------------------------------------------------------
# NOTEBOOK 06 — Multiple Testing
# ---------------------------------------------------------------------------

NB06 = notebook([
    md(
        '# 06 — Multiple Testing Correction',
        '',
        'Every time we run a hypothesis test at α=0.05, we accept a 5% false positive rate.',
        'If we run **k** tests, the probability of at least one false positive grows rapidly.',
        '',
        'This notebook covers:',
        '',
        '1. **The inflation problem** — simulating false positives under the null',
        '2. **Family-wise error rate (FWER)** — the probability of any false positive',
        '3. **Bonferroni correction** — the simplest FWER control',
        '4. **Holm-Bonferroni** — a uniformly more powerful stepwise alternative',
        '5. **Benjamini-Hochberg FDR** — controlling the *rate* of false positives',
        '6. **Practical guidance** — when to use each method',
    ),

    code(
        'import sys',
        'import numpy as np',
        'import pandas as pd',
        'import matplotlib.pyplot as plt',
        'import seaborn as sns',
        'from scipy import stats',
        '',
        'sys.path.append("../src")',
        'from ab_stats import bonferroni_correct, benjamini_hochberg',
        '',
        'sns.set_theme(style="whitegrid", palette="muted")',
        'plt.rcParams["figure.dpi"] = 120',
        '',
        'np.random.seed(42)',
        'ALPHA = 0.05',
    ),

    md(
        '## 1. The Inflation Problem',
        '',
        'Suppose we test 20 metrics, none of which are truly affected by the treatment.',
        'Under the null hypothesis, each test has a 5% chance of a false positive.',
        '',
        '$$P(\\text{at least one false positive}) = 1 - (1 - 0.05)^{20} \\approx 64\\%$$',
        '',
        "That's not a p-value problem — it's a *multiple comparisons* problem.",
    ),

    code(
        '# Simulate 10,000 experiments, each testing k null metrics',
        'k_values = [1, 5, 10, 20, 50, 100]',
        'fwer = [1 - (1 - ALPHA)**k for k in k_values]',
        '',
        'fig, ax = plt.subplots(figsize=(8, 4))',
        'ax.plot(k_values, [f*100 for f in fwer], marker="o", color="tomato", linewidth=2)',
        'ax.axhline(5, color="steelblue", linestyle="--", linewidth=1.2, label="Nominal α=5%")',
        'ax.set_xlabel("Number of tests (k)")',
        'ax.set_ylabel("P(at least one false positive) %")',
        'ax.set_title("Family-wise error rate grows with number of tests")',
        'ax.legend()',
        'for k, f in zip(k_values, fwer):',
        '    ax.annotate(f"{f:.0%}", (k, f*100), textcoords="offset points", xytext=(0, 8),',
        '                ha="center", fontsize=9)',
        'plt.tight_layout()',
        'plt.show()',
    ),

    code(
        '# Simulate false positives empirically',
        'n_sims = 10_000',
        'k = 20',
        'n_per_group = 5_000',
        '',
        'false_pos_counts = []',
        'for _ in range(n_sims):',
        '    p_values = []',
        '    for _ in range(k):',
        '        g1 = np.random.binomial(1, 0.12, n_per_group)',
        '        g2 = np.random.binomial(1, 0.12, n_per_group)  # null: same rate',
        '        _, pv = stats.ttest_ind(g1, g2)',
        '        p_values.append(pv)',
        '    false_pos_counts.append(sum(p < ALPHA for p in p_values))',
        '',
        'any_false_pos = np.mean([c > 0 for c in false_pos_counts])',
        'print(f"Simulated FWER with k={k} tests: {any_false_pos:.2%}")',
        'print(f"Theoretical FWER:               {1-(1-ALPHA)**k:.2%}")',
    ),

    md(
        '## 2. Bonferroni Correction',
        '',
        'The simplest approach: divide α by the number of tests.',
        '',
        '$$\\alpha_{\\text{adjusted}} = \\frac{\\alpha}{k}$$',
        '',
        'A test is significant only if its p-value is below the adjusted threshold.',
        '',
        '**Pros:** Simple, controls FWER strongly',
        '**Cons:** Very conservative — inflates Type II errors (misses real effects)',
        'when tests are positively correlated',
    ),

    code(
        '# Apply to our segment p-values from notebook 05',
        'segment_results = {',
        '    "Weekday":   0.312,',
        '    "Weekend":   0.421,',
        '    "Monday":    0.189,',
        '    "Tuesday":   0.743,',
        '    "Wednesday": 0.051,',
        '    "Thursday":  0.088,',
        '    "Friday":    0.034,   # looks significant unadjusted!',
        '    "Saturday":  0.291,',
        '    "Sunday":    0.578,',
        '}',
        '',
        'names   = list(segment_results.keys())',
        'p_vals  = np.array(list(segment_results.values()))',
        '',
        'adj_alpha, bonf_rejected, bonf_p = bonferroni_correct(p_vals, ALPHA)',
        'print(f"Bonferroni adjusted alpha: {adj_alpha:.4f}")',
        'print()',
        'print("{:<12} {:>10} {:>10} {:>10}".format("Segment", "p-value", "Bonf p", "Rejected"))',
        'print("-" * 46)',
        'for name, p, bp, rej in zip(names, p_vals, bonf_p, bonf_rejected):',
        '    flag = "* SIGNIFICANT" if rej else ""',
        '    print(f"{name:<12} {p:>10.4f} {min(bp,1):>10.4f} {str(rej):>10} {flag}")',
    ),

    md(
        '## 3. Holm-Bonferroni (Stepwise)',
        '',
        'Sort p-values from smallest to largest. Compare each to α/(k−rank+1) instead of α/k.',
        'Stop as soon as a test is not rejected — all remaining are also not rejected.',
        '',
        'This is uniformly more powerful than Bonferroni (never worse, often better)',
        'while still controlling FWER.',
    ),

    code(
        'order = np.argsort(p_vals)',
        'k = len(p_vals)',
        'holm_rejected = np.zeros(k, dtype=bool)',
        '',
        'print("{:<6} {:<12} {:>10} {:>12} {:>10}".format("Rank", "Segment", "p-value", "Threshold", "Rejected"))',
        'print("-" * 54)',
        '',
        'stop = False',
        'for rank, idx in enumerate(order):#, 1):',
        '    threshold = ALPHA / (k - rank)',
        '    if not stop and p_vals[idx] < threshold:',
        '        holm_rejected[idx] = True',
        '    else:',
        '        stop = True',
        '    print(f"{rank+1:<6} {names[idx]:<12} {p_vals[idx]:>10.4f} {threshold:>12.4f} {str(holm_rejected[idx]):>10}")',
        '',
        'print()',
        'print(f"Bonferroni rejections: {bonf_rejected.sum()} | Holm rejections: {holm_rejected.sum()}")',
    ),

    md(
        '## 4. Benjamini-Hochberg FDR',
        '',
        'Instead of controlling **FWER** (any false positive), BH controls the',
        '**False Discovery Rate** — the *expected proportion* of rejections that are false.',
        '',
        '$$FDR = E\\left[\\frac{\\text{false positives}}{\\text{total rejections}}\\right]$$',
        '',
        'This is less stringent than Bonferroni — appropriate when you are OK with',
        'some false positives as long as most findings are real.',
        '',
        '**Use BH when:** exploring many features, genes, or segments in an discovery context',
        '**Use Bonferroni/Holm when:** confirmatory testing where any false positive is costly',
    ),

    code(
        'bh_rejected, bh_p = benjamini_hochberg(p_vals, ALPHA)',
        '',
        'print("{:<12} {:>10} {:>10} {:>10}".format("Segment", "p-value", "BH adj p", "Rejected"))',
        'print("-" * 46)',
        'for name, p, bp, rej in zip(names, p_vals, bh_p, bh_rejected):',
        '    flag = "* SIGNIFICANT" if rej else ""',
        '    print(f"{name:<12} {p:>10.4f} {bp:>10.4f} {str(rej):>10} {flag}")',
    ),

    code(
        '# Visual comparison of all three methods',
        'fig, ax = plt.subplots(figsize=(10, 5))',
        '',
        'y = np.arange(len(names))',
        'order_display = np.argsort(p_vals)',
        'sorted_names = [names[i] for i in order_display]',
        'sorted_p     = p_vals[order_display]',
        'sorted_bonf  = bonf_rejected[order_display]',
        'sorted_holm  = holm_rejected[order_display]',
        'sorted_bh    = bh_rejected[order_display]',
        '',
        'ax.barh(y, sorted_p, color="lightgray", edgecolor="white")',
        'ax.axvline(ALPHA,              color="gray",     linestyle=":",  linewidth=1.5, label=f"Unadjusted α={ALPHA}")',
        'ax.axvline(adj_alpha,          color="tomato",   linestyle="--", linewidth=1.5, label=f"Bonferroni α={adj_alpha:.4f}")',
        '',
        'for i, (bp, hp, bhp) in enumerate(zip(sorted_bonf, sorted_holm, sorted_bh)):',
        '    markers = []',
        '    if bhp:   markers.append(("BH",       "green",     0.82))',
        '    if hp:    markers.append(("Holm",     "orange",    0.88))',
        '    if bp:    markers.append(("Bonf",     "tomato",    0.94))',
        '    for label, color, xpos in markers:',
        '        ax.text(xpos, i, label, color=color, fontsize=7, va="center")',
        '',
        'ax.set_yticks(y)',
        'ax.set_yticklabels(sorted_names)',
        'ax.set_xlabel("p-value")',
        'ax.set_title("Segment p-values with multiple testing thresholds")',
        'ax.legend(loc="lower right")',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## 5. Practical Guidance',
        '',
        '| Scenario | Method | Why |',
        '|---|---|---|',
        '| 1–3 pre-specified primary metrics | None needed | Pre-registration handles it |',
        '| Many confirmatory tests, costly false positives | Bonferroni or Holm | Strong FWER control |',
        '| Exploratory segment mining | Benjamini-Hochberg | FDR is appropriate for discovery |',
        '| Sequential peeking (multiple looks) | Alpha spending (O\'Brien-Fleming) | Covered in extensions |',
        '',
        '**The best defense against multiple testing problems is pre-registration:**',
        'commit to your primary metric and planned segments *before* launch.',
        'Post-hoc findings are exploratory, not confirmatory — label them accordingly.',
        '',
        'Proceed to **[07 — Business Impact](07_business_impact.ipynb)**.',
    ),
])

# ---------------------------------------------------------------------------
# NOTEBOOK 07 — Business Impact
# ---------------------------------------------------------------------------

NB07 = notebook([
    md(
        '# 07 — Business Impact',
        '',
        'Statistical results need to be translated into business decisions.',
        'A p-value alone cannot tell a product manager what to do.',
        '',
        'This notebook covers:',
        '',
        '1. **Revenue impact of the observed lift** — point estimate',
        '2. **Confidence interval on revenue** — range of plausible outcomes',
        '3. **Expected value framework** — weighing uncertain impact against shipping cost',
        '4. **Experiment ROI** — was running this test worth it?',
        '5. **Decision narrative** — what to actually say in the readout',
        '6. **Experiment write-up template** — repeatable format for every test',
    ),

    code(
        'import sys',
        'import numpy as np',
        'import pandas as pd',
        'import matplotlib.pyplot as plt',
        'import seaborn as sns',
        'from scipy import stats',
        '',
        'sys.path.append("../src")',
        'from ab_stats import two_proportion_ztest',
        '',
        'sns.set_theme(style="whitegrid", palette="muted")',
        'plt.rcParams["figure.dpi"] = 120',
        '',
        'ALPHA = 0.05',
        '',
        '# Business parameters — adjust to your actual context',
        'WEEKLY_VISITORS     = 50_000   # new visitors per week',
        'REVENUE_PER_CONVERT = 40       # average revenue per converted user ($)',
        'SHIP_COST           = 5_000    # estimated one-time engineering cost to ship ($)',
        '',
        'df = pd.read_csv("../data/ab_data_clean.csv")',
        'grp = df.groupby("group")["converted"].agg(conversions="sum", users="count")',
        'grp["rate"] = grp["conversions"] / grp["users"]',
        'ctrl, trt = grp.loc["control"], grp.loc["treatment"]',
        '',
        'z, p_val, p_c, p_t, lift_abs, lift_rel = two_proportion_ztest(',
        '    ctrl.conversions, ctrl.users, trt.conversions, trt.users',
        ')',
        '',
        'print(f"Control rate:   {p_c:.4%}")',
        'print(f"Treatment rate: {p_t:.4%}")',
        'print(f"Absolute lift:  {lift_abs:+.4%}")',
        'print(f"p-value:        {p_val:.4f}")',
    ),

    md('## 1. Revenue Impact — Point Estimate'),

    code(
        '# Point estimate: weekly incremental revenue',
        'incremental_weekly_conversions = lift_abs * WEEKLY_VISITORS',
        'incremental_weekly_revenue     = incremental_weekly_conversions * REVENUE_PER_CONVERT',
        'incremental_annual_revenue     = incremental_weekly_revenue * 52',
        '',
        'print("=" * 50)',
        'print("  Revenue Impact — Point Estimate")',
        'print("=" * 50)',
        'print(f"  Observed lift            : {lift_abs:+.4%}")',
        'print(f"  Weekly visitors          : {WEEKLY_VISITORS:,}")',
        'print(f"  Incremental conversions/week: {incremental_weekly_conversions:+,.0f}")',
        'print(f"  Revenue per conversion   : ${REVENUE_PER_CONVERT:,}")',
        'print(f"  Incremental revenue/week : ${incremental_weekly_revenue:+,.0f}")',
        'print(f"  Incremental revenue/year : ${incremental_annual_revenue:+,.0f}")',
        'print("=" * 50)',
    ),

    md(
        '## 2. Confidence Interval on Revenue',
        '',
        'Point estimates are misleading on their own. The CI on the lift translates directly',
        'into a CI on annual revenue — giving decision-makers a range, not a false precision.',
    ),

    code(
        'se_diff = np.sqrt(p_c*(1-p_c)/ctrl.users + p_t*(1-p_t)/trt.users)',
        'z_crit  = stats.norm.ppf(1 - ALPHA/2)',
        'diff_lo = lift_abs - z_crit * se_diff',
        'diff_hi = lift_abs + z_crit * se_diff',
        '',
        'rev_lo = diff_lo * WEEKLY_VISITORS * REVENUE_PER_CONVERT * 52',
        'rev_hi = diff_hi * WEEKLY_VISITORS * REVENUE_PER_CONVERT * 52',
        '',
        'print(f"95% CI on lift:           [{diff_lo:+.4%}, {diff_hi:+.4%}]")',
        'print(f"95% CI on annual revenue: [${rev_lo:+,.0f}, ${rev_hi:+,.0f}]")',
        '',
        '# Visualize revenue distribution',
        'lift_samples = np.random.normal(lift_abs, se_diff, 50_000)',
        'rev_samples  = lift_samples * WEEKLY_VISITORS * REVENUE_PER_CONVERT * 52',
        '',
        'fig, ax = plt.subplots(figsize=(9, 4))',
        'ax.hist(rev_samples / 1000, bins=80, color="steelblue", alpha=0.7, density=True)',
        'ax.axvline(0, color="gray", linewidth=1.5, linestyle="--", label="No impact")',
        'ax.axvline(incremental_annual_revenue/1000, color="darkgreen", linewidth=2,',
        '           label=f"Point estimate: ${incremental_annual_revenue/1000:+.0f}k")',
        'ax.axvline(rev_lo/1000, color="tomato", linewidth=1.5, linestyle=":",',
        '           label=f"95% CI lower: ${rev_lo/1000:+.0f}k")',
        'ax.axvline(rev_hi/1000, color="tomato", linewidth=1.5, linestyle=":",',
        '           label=f"95% CI upper: ${rev_hi/1000:+.0f}k")',
        'ax.set_xlabel("Annual incremental revenue ($k)")',
        'ax.set_ylabel("Density")',
        'ax.set_title("Distribution of plausible annual revenue impacts")',
        'ax.legend(fontsize=9)',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## 3. Expected Value Framework',
        '',
        'When the result is uncertain (p > 0.05, CI spans zero), expected value helps frame',
        'the decision by weighing the probability of a positive effect against its magnitude.',
        '',
        '$$EV[\\text{ship}] = P(\\text{positive}) \\times \\text{upside} + P(\\text{negative}) \\times \\text{downside} - \\text{shipping cost}$$',
        '',
        'If EV[ship] > 0 → lean toward shipping.',
        'If EV[ship] < 0 → lean toward not shipping or running a larger experiment.',
    ),

    code(
        '# Proportion of the revenue distribution that is positive',
        'p_positive = np.mean(rev_samples > 0)',
        'p_negative = 1 - p_positive',
        '',
        'mean_upside   = rev_samples[rev_samples > 0].mean() if p_positive > 0 else 0',
        'mean_downside = rev_samples[rev_samples < 0].mean() if p_negative > 0 else 0',
        '',
        'ev_ship = p_positive * mean_upside + p_negative * mean_downside - SHIP_COST',
        '',
        'print(f"P(positive annual revenue) : {p_positive:.1%}")',
        'print(f"E[revenue | positive]      : ${mean_upside:,.0f}")',
        'print(f"P(negative annual revenue) : {p_negative:.1%}")',
        'print(f"E[revenue | negative]      : ${mean_downside:,.0f}")',
        'print(f"Shipping cost              : ${SHIP_COST:,}")',
        'print()',
        'print(f"E[value of shipping]       : ${ev_ship:,.0f}")',
        'print()',
        'if ev_ship > 0:',
        '    print("Expected value is POSITIVE — lean toward shipping despite uncertainty.")',
        'else:',
        '    print("Expected value is NEGATIVE — lean toward NOT shipping, or run a larger test.")',
    ),

    md(
        '## 4. Experiment ROI',
        '',
        'Running the experiment itself has a cost — engineering time, traffic allocation',
        '(some users got the worse experience), and analyst time.',
        '',
        'The **value of information** from the experiment is the difference between the',
        'best decision we can make *with* the data vs. *without* it.',
    ),

    code(
        'experiment_cost = 15_000   # est: eng time + analyst time ($)',
        '',
        '# Without the experiment: we either ship blindly or do nothing',
        '# With the experiment: we have evidence to inform the decision',
        '',
        '# Cost of a wrong decision (shipping a page that hurts): magnitude of downside',
        'cost_of_wrong_ship = abs(mean_downside) if p_negative > 0 else 0',
        '',
        '# Value of knowing before shipping = expected cost avoided by not shipping a bad change',
        'value_of_info = p_negative * cost_of_wrong_ship',
        '',
        'print(f"Experiment cost        : ${experiment_cost:>10,.0f}")',
        'print(f"Value of information   : ${value_of_info:>10,.0f}")',
        'print(f"Net experiment ROI     : ${value_of_info - experiment_cost:>+10,.0f}")',
        'print()',
        'print("Note: this is a simplified VOI calculation.")',
        'print("Full Bayesian VOI analysis accounts for prior beliefs about effect sizes.")',
    ),

    md(
        '## 5. The Decision Narrative',
        '',
        'Every experiment should end with a clear, written decision — not just numbers.',
        'Here is the narrative for our experiment.',
        '',
        '---',
        '',
        '### Experiment Readout: Landing Page Redesign',
        '',
        '**Result:** The new landing page did not produce a statistically significant change',
        'in conversion rate (p = 0.19, 95% CI on lift: [−0.5%, +0.1%]).',
        '',
        '**What this means:** We cannot conclude the new page improves or worsens conversion.',
        'The observed −0.2pp difference is within the range expected from random variation.',
        '',
        '**What this does NOT mean:** The page has no effect. We may lack the statistical power',
        'to detect effects smaller than ±0.3pp with our current traffic.',
        '',
        '**Recommendation:** Do not ship the redesign based on this experiment.',
        'Options:',
        '1. Run a larger experiment (targeting 2pp MDE with 80% power requires ~7,600 users per group)',
        '2. Redesign the treatment to make a more substantial change before re-testing',
        '3. Investigate whether specific segments (mobile, new users) respond differently',
        '',
        '---',
    ),

    code(
        '# Final summary visualization',
        'fig, axes = plt.subplots(1, 3, figsize=(13, 4))',
        '',
        '# 1. Conversion rates',
        'ax = axes[0]',
        'ax.bar(["Control", "Treatment"], [p_c*100, p_t*100], color=["steelblue","coral"], width=0.5)',
        'ax.set_ylabel("Conversion rate (%)")',
        'ax.set_title("Conversion rates")',
        'ax.set_ylim(10, 14)',
        'for i, (r, label) in enumerate([(p_c, "Control"),(p_t, "Treatment")]):',
        '    ax.text(i, r*100 + 0.05, f"{r:.2%}", ha="center", fontweight="bold")',
        '',
        '# 2. CI on lift',
        'ax = axes[1]',
        'ax.axvline(0, color="gray", linewidth=1.5, linestyle="--")',
        'ax.errorbar(lift_abs*100, 0.5,',
        '            xerr=[[abs(diff_lo-lift_abs)*100],[abs(diff_hi-lift_abs)*100]],',
        '            fmt="o", color="steelblue", capsize=10, markersize=9, linewidth=2.5)',
        'ax.set_yticks([])',
        'ax.set_xlabel("Lift (pp)")',
        'ax.set_title("95% CI on lift")',
        '',
        '# 3. Revenue distribution',
        'ax = axes[2]',
        'ax.hist(rev_samples/1000, bins=60, color="steelblue", alpha=0.6, density=True)',
        'ax.axvline(0, color="tomato", linewidth=1.5, linestyle="--")',
        'ax.set_xlabel("Annual revenue impact ($k)")',
        'ax.set_title("Revenue uncertainty")',
        '',
        'plt.suptitle("Experiment Summary: Landing Page Redesign", fontsize=13, fontweight="bold")',
        'plt.tight_layout()',
        'plt.show()',
    ),

    md(
        '## 6. Experiment Write-Up Template',
        '',
        'Use this structure for every experiment readout:',
        '',
        '```',
        '## Experiment: [Name]',
        '',
        '**Hypothesis:** [What we expected and why]',
        '**Treatment:** [What changed]',
        '**Primary metric:** [Metric name and formula]',
        '**Date range:** [Start] – [End]  |  **N:** [Control] / [Treatment]',
        '',
        '### Results',
        '| Metric | Control | Treatment | Lift | p-value | Significant? |',
        '|--------|---------|-----------|------|---------|--------------|',
        '| [primary] | | | | | |',
        '| [guardrail 1] | | | | | |',
        '',
        '### Decision',
        '[Ship / Do not ship / Inconclusive — retest]',
        '',
        '### Why',
        '[2–3 sentences translating the stats into business language]',
        '',
        '### Next steps',
        '[Concrete follow-up actions]',
        '```',
        '',
        '---',
        '',
        '## End of Portfolio',
        '',
        'You have now seen the full A/B testing lifecycle:',
        '',
        '| Notebook | Concept |',
        '|---|---|',
        '| 01 | Experiment design — hypothesis, MDE, sample size |',
        '| 02 | Data validation — SRM, deduplication, mismatches |',
        '| 03 | Statistical analysis — z-test, p-values, CIs |',
        '| 04 | Practical significance — effect size, decision quadrants |',
        '| 05 | Segment analysis — Simpson\'s Paradox, interaction effects |',
        '| 06 | Multiple testing — Bonferroni, BH-FDR |',
        '| 07 | Business impact — revenue CIs, expected value, decision narrative |',
        '',
        'The full code is reusable via `src/ab_stats.py`.',
    ),
])

# ---------------------------------------------------------------------------
# Write all notebooks to disk
# ---------------------------------------------------------------------------

notebooks = {
    '02_data_validation.ipynb':      NB02,
    '03_statistical_analysis.ipynb': NB03,
    '04_practical_significance.ipynb': NB04,
    '05_segment_analysis.ipynb':     NB05,
    '06_multiple_testing.ipynb':     NB06,
    '07_business_impact.ipynb':      NB07,
}

for filename, nb in notebooks.items():
    path = os.path.join(NOTEBOOKS_DIR, filename)
    with open(path, 'w') as f:
        json.dump(nb, f, indent=1)
    print(f'Written: {path}')

print('\nAll notebooks generated.')
